<template>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>

  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>

  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>

  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>

  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>
  <section>
    <p>TheControls</p>
  </section>
  <section>
    <p>TheBoard</p>
  </section>
  <section>
    <p>NumberInputs</p>
  </section>
  <section>
    <p>RecordsTable</p>
  </section>

</template>
<script setup lang="ts">

</script>
